---
# handlers file for k8s-nodes-prepare

- name: Restart containerd
  ansible.builtin.service:
    name: containerd
    state: restarted
    enabled: true

- name: Restart NetworkManager
  ansible.builtin.systemd:
    name: NetworkManager
    state: restarted
    enabled: true
