- name: Copy Kubernetes configuration to local machine
  hosts: masters
  gather_facts: true
  become: true

  tasks:
    - name: Fetch kube config from master nodes
      ansible.builtin.fetch:
        src: "/home/vagrant/.kube/config"
        dest: "{{ lookup('env', 'HOME') }}/.kube/{{ inventory_hostname }}-kubeconfig"
        flat: true
