---
- name: Get join command from master
  hosts: masters
  become: true
  gather_facts: false
  tasks:
    - name: Get join command
      ansible.builtin.command: kubeadm token create --print-join-command
      register: join_command_raw
      changed_when: false

    - name: Set join command
      ansible.builtin.set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- name: Join workers to master
  hosts: workers
  become: true
  tasks:
    - name: Join cluster
      ansible.builtin.shell: "{{ hostvars['10.0.0.10'].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt
